---

platform: linux

image_resource:
  type: docker-image
  source:
    repository: golang
    tag: 1.24.2-bullseye

inputs:
  - name: dp-developer-site

outputs:
  - name: build

caches:
  - path: go/

run:
  path: dp-developer-site/ci/scripts/build.sh
