---

platform: linux

image_resource:
  type: docker-image
  source:
    repository: onsdigital/dp-concourse-tools-node-go

inputs:
  - name: dp-developer-site
    path: go/src/github.com/ONSdigital/dp-developer-site

outputs:
  - name: build

run:
  path: go/src/github.com/ONSdigital/dp-developer-site/ci/scripts/build.sh
