---

platform: linux

image_resource:
  type: docker-image
  source:
    repository: onsdigital/dp-concourse-tools-node-go
    tag: 1.24.9-bookworm-node-20

inputs:
  - name: dp-developer-site

outputs:
  - name: build

caches:
  - path: go/

run:
  path: dp-developer-site/ci/scripts/build.sh
